### ISSUE TITLE
Octoprint plugin

### ISSUE THREAD

**Issue by Brandoskey** [syue87/GCodeAnalyser#1] opened 2017-12-02 17:31 UTC
Any chance of this becoming an octoprint plugin?

**Comment by syue87** [comment] 2017-12-07 17:29
Making it a octoprint plugin is requires a lot of work. The two main problems are:
1. Octoprint plugins are written in Python, the current project is written in Javascript. So I cannot reuse any of the existing code.
2. Octoprint runs on raspberry pi, which has very limited resource comparing to a PC. The code needs to be optimized.

I will consider making it a octoprint plugin when I have some free time, but it will definatly take some time.

**Comment by joshfria** [comment] 2018-01-03 23:31
Why not just have it call on the website with parameters input to a menu?

**Comment by syue87** [comment] 2018-01-04 06:43
@joshfria 
I'm not exactly sure what you mean. If you are talking about redirecting to the website from octoprint plugin, I've though about that. The problem is that the gcode is on the raspberry board, it might take a lot of time to upload the gcode.

**Comment by joshfria** [comment] 2018-01-04 15:05
It shouldn't be any slower to upload than a computer. Gcode is typically under 20-30MB except on really large jobs. Could you not run your javascript through a converter like https://github.com/PiotrDabkowski/Js2Py?

**Comment by syue87** [comment] 2018-01-05 18:09
@joshfria 
The raspberry pi has very limited resource comparing to a PC. Currently the program uses up to a few GB of memory on larger gcodes. In order for the code to run at reasonable speed, I would have to manually write optimized code in python and specifically for the raspberry pi. And like I said, I currently don't have the time to work on this, I will look into it in the future.

**Comment by derboehsevincent** [comment] 2018-04-23 17:59
Just to push this a little bit ;) Python is just the framework in this case. Most of the plugins do the computation stuff in js.

**Comment by QuickChemist** [comment] 2018-06-11 03:40
Hoping for this as well

**Comment by eyal0** [comment] 2018-06-27 13:00
Have you tried running it as-is on RPi 3 with nodejs? What is the speed as compared to desktop?

**Comment by eyal0** [comment] 2018-07-02 19:02
I tested it on RPi.  It's about 8 times slower than my computer.  Not too horrible...

**Comment by syue87** [comment] 2018-07-02 20:45
@eyal0 The program could take more memory then RPi 3 has with large gcode files, in which case the speed will be even slower than that.
The V2 I'm working on will use much less memory, and have APIs to accept data stream from Octoprint plugin.

**Comment by eyal0** [comment] 2018-07-03 05:20
Do you have sample large gcode files that use too much memory? In my testing, all large files worked. I'm also able to run Slic3r on really big files on RPi.

What will the OctoPrint plugin do?

**Comment by syue87** [comment] 2018-07-03 21:46
I don't have the gcode anymore. The one I used for testing is a little over 100MB.
The plug in will add a button beside the gcode files, once clicked it will open a gcodeanalyser window. The code file and settings will be automatically transferred over.

**Comment by eyal0** [comment] 2018-07-04 13:05
Okay, so it would just run the analysis and that's it?  Would it incorporate the results into OctoPrint somehow?  For example, a better estimated print time?

**Comment by syue87** [comment] 2018-07-26 23:16
I can probably write the result back to OctoPrint. I'll have more detail when I start working on it, I haven't really give too much thought yet.

**Comment by syue87** [comment] 2018-11-12 00:41
I'm working on another project that will support gcode processing on the server side, it's a better candidate for Octoprint plugin support. Processing gcode will remain in the browser on the client side for this project.

**Closed as completed by syue87** 2018-11-12 00:41 UTC
